defmodule MobDev.Plugin.RuntimeManifest do
  @moduledoc """
  Builds the host's **runtime plugin manifest** — the device-readable record of
  the activated plugins' tier-3/4 contributions.

  Tiers 3 and 4 are pure-Elixir and runtime-wired: the host needs to know, on
  device, which screens exist, what lifecycle/settings/notification declarations
  each plugin made — but `MobDev.Plugin.activated/0` is compile-time only. So at
  build time this module gathers those sections (running any spec-v2
  `:screens_generator` under the host-config audit) and emits a terms file
  (`priv/generated/mob_plugins.exs`) that the core `Mob.Plugins` module reads at
  boot. It mirrors the `driver_tab` / `MobPluginBootstrap` codegen pattern, but
  for serializable Elixir data instead of native symbols.

  Only the behavioral data lives here. Migration files and font/image assets are
  physically copied into the host at build time (see `native_build`), not carried
  in this manifest.

  Everything emitted must be serializable terms — atoms, tuples, maps, strings,
  integers. The manifest validator forbids closures in plugin sections so this
  always holds.
  """

  alias MobDev.Plugin.Merge

  @doc """
  Builds the merged runtime manifest map from `{plugin_dir, manifest}` pairs.

  Static `:screens` and spec-v2 `:screens_generator` output are combined (each
  tagged with its plugin); generators run under `MobDev.Plugin.with_host_config_audit/3`
  so an undeclared host-config read fails the build.
  """
  @spec build([{Path.t(), map() | nil}]) :: map()
  def build(plugins) do
    %{
      screens: Merge.screens(plugins) ++ generated_screens(plugins),
      lifecycle: Merge.lifecycle(plugins),
      settings: Merge.settings(plugins),
      notification_handlers: Merge.notification_handlers(plugins)
    }
  end

  defp generated_screens(plugins) do
    for {_dir, manifest} <- plugins,
        is_map(manifest),
        gen = manifest[:screens_generator],
        not is_nil(gen) do
      {m, f, a} = gen
      allowed = manifest[:host_config_keys] || []

      {screens, _reads} =
        MobDev.Plugin.with_host_config_audit(manifest[:name], allowed, fn -> apply(m, f, a) end)

      for s <- List.wrap(screens), is_map(s), do: Map.put(s, :plugin, manifest[:name])
    end
    |> List.flatten()
  end

  @doc """
  Renders the manifest map to the contents of `priv/generated/mob_plugins.exs` —
  a self-describing `.exs` that evaluates back to the map.
  """
  @spec render(map()) :: String.t()
  def render(manifest) do
    """
    # Generated by `mix mob.regen_plugin_manifest` — do not edit by hand.
    #
    # The activated plugins' tier-3/4 contributions, read at boot by Mob.Plugins.
    # Regenerated whenever `config :mob, :plugins` changes (the deploy/regen hook).
    #{inspect(manifest, limit: :infinity, printable_limit: :infinity, pretty: true)}
    """
  end

  @doc """
  Writes the rendered manifest to `<host_root>/priv/generated/mob_plugins.exs`
  and returns the path.
  """
  @spec write(Path.t(), map()) :: Path.t()
  def write(host_root, manifest) do
    path = Path.join([host_root, "priv", "generated", "mob_plugins.exs"])
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, render(manifest))
    path
  end
end
